language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
jobs:
  include:
    - stage: code check
      script: 
      - python YouKnowShit/CheckFile.py
      - scrapy runspider thzspider/spiders/myspider.py
    - stage: run spider on scrapinghub
      script: 'curl -u 11befd9da9304fecb83dfa114d1926e9: https://app.scrapinghub.com/api/run.json -d project=Thz -d spider=thz'
# slack
notifications:
  slack: jiangtianyu:s5kgWEw0Mmf0PhlYniLoT8Sv