language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
jobs:
  include:
    - stage: run javlib name spider on travis-ci
      script: 
      - scrapy runspider thzspider/spiders/namespider.py
    - stage: run javlib code spider on travis-ci
      script: 
      - scrapy runspider thzspider/spiders/codespider.py
    - stage: run ride spider on travis-ci
      script: 
      - scrapy runspider thzspider/spiders/ridespider.py
    - stage: run walk spider on travis-ci
      script: 
      - scrapy runspider thzspider/spiders/walkspider.py
    - stage: run my spider on travis-ci
      script: 
      - scrapy runspider thzspider/spiders/myspider.py
    - stage: run spider on scrapinghub
      script: 
      - python thzspider/scripts/runonscrapinghub.py
# slack
notifications:
  slack: jiangtianyu:s5kgWEw0Mmf0PhlYniLoT8Sv