language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python checkfiles.py
# command to run tests
jobs:
  include:
    - stage: run spider on scrapinghub
      script: 
      - python thzspider/scripts/runonscrapinghub.py
# slack
# notifications:
#   slack: jiangtianyu:s5kgWEw0Mmf0PhlYniLoT8Sv