language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python YouKnowShit/CheckFile.py
  - scrapy runspider thzspider/spiders/myspider.py
notifications:
  slack: jiangtianyu:s5kgWEw0Mmf0PhlYniLoT8Sv